### ISSUE TITLE
ImportError: cannot import name 'mobilenet_v3' from 'torchvision.models'

### ISSUE THREAD

**Issue by EstebanAguayo** [alexciru/mlops-finalProject#6]
Hey guys I am having an issue importing the model. After some reading it seems that my torch verison may be outdated. I will keep you updated.
Current torch version: 1.13.1

**Comment by EstebanAguayo** [comment]
https://github.com/pytorch/vision/blob/main/torchvision/models/mobilenetv3.py

I could create a file with the whole model

**Comment by alexciru** [comment]
I think the issue with the import model was fixed👌
